#!/usr/bin/env python3
"""Inline every JSX + CSS file referenced by Kickstand.html into a single
self-contained Kickstand Preview.html.

Why: Babel-in-browser fetches each `<script src=…>` via XHR, which Chrome
blocks under the `file://` protocol. Inlining sidesteps that — the resulting
single file double-clicks open in any browser. That's the file we ship to
schools as the marketing-site preview.

Re-run after editing any of the `app/*.jsx` files:

    python3 design_handoff_kickstand/bundle.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent
SOURCE = ROOT / "Kickstand.html"
OUT = ROOT / "Kickstand Preview.html"

# Same script load order as Kickstand.html. Kept here so the bundler is
# the canonical source — if you add a JSX module, add it both here and in
# Kickstand.html.
SCRIPTS = [
    "frames/ios-frame.jsx",
    "frames/browser-window.jsx",
    "frames/tweaks-panel.jsx",
    "app/icons.jsx",
    "app/ui.jsx",
    "app/data.jsx",
    "app/data2.jsx",
    "app/notifications.jsx",
    "app/auth.jsx",
    "app/student-book.jsx",
    "app/student.jsx",
    "app/instructor.jsx",
    "app/admin-fleet.jsx",
    "app/admin-students.jsx",
    "app/admin-signups.jsx",
    "app/admin-pay.jsx",
    "app/admin.jsx",
    "app/shell.jsx",
]
TOKENS_CSS = "app/tokens.css"


def main() -> int:
    html = SOURCE.read_text()

    # 1. Replace the <link href="app/tokens.css"> with an inline <style>.
    tokens = (ROOT / TOKENS_CSS).read_text()
    html = re.sub(
        r'<link\s+rel="stylesheet"\s+href="app/tokens.css"\s*/?>',
        f"<style>\n{tokens}\n</style>",
        html,
    )

    # 2. Replace every `<script type="text/babel" src="…"></script>` with
    # the file inlined. Same order as SCRIPTS — we walk one-by-one so the
    # first regex match always targets the next script in the load order.
    for src in SCRIPTS:
        body = (ROOT / src).read_text()
        # Escape any `</script` inside the body so it can't terminate our
        # outer script tag early. Rare in practice but defensive.
        body = body.replace("</script", "<\\/script")
        replacement = (
            f"<script type=\"text/babel\" data-original-src=\"{src}\">\n"
            f"{body}\n"
            f"</script>"
        )
        pattern = re.compile(
            rf'<script\s+type="text/babel"\s+src="{re.escape(src)}"\s*></script>'
        )
        # Use a lambda for the replacement so any `\u…` / `\n` sequences in
        # the JSX body don't get interpreted as regex back-references.
        new_html, n = pattern.subn(lambda _m, r=replacement: r, html, count=1)
        if n == 0:
            print(f"!! Could not find a placeholder for {src} in Kickstand.html",
                  file=sys.stderr)
            return 1
        html = new_html

    # 3. Add a tiny breadcrumb at the top of the file so anyone opening the
    # raw HTML can tell it's generated.
    html = html.replace(
        "<!DOCTYPE html>",
        "<!DOCTYPE html>\n<!-- Generated by design_handoff_kickstand/bundle.py — "
        "do not edit by hand. Re-run after editing any app/*.jsx file. -->",
        1,
    )

    OUT.write_text(html)
    kb = OUT.stat().st_size / 1024
    print(f"wrote {OUT.relative_to(ROOT.parent)} ({kb:,.1f} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
